sudo: false

language: node_js
node_js:
    - "12"

services:
    - docker

notifications:
    email: false

branches:
    only:
        - master

cache:
    directories:
        - ./node_modules
        - ./dist

before_script:
    - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd

before_install:
    - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $TRAVIS_SECURE_ENV_VARS == "true" ]] ; then
       openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .ssh/id_rsa.enc -out ~/.ssh/id_rsa -d &&
       chmod 600 ~/.ssh/id_rsa;
     fi'

install:
    - npm install -g @nestjs/cli

jobs:
    include:
        - stage: tests
          script:
              - make build license_check lint
        - stage: release
          if: type != pull_request && fork == false
          script:
              - bash ./build/bin/push-images
              - bash ../build-tools/release-merge-commit

